name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Compile TypeScript files
      - name: Compile TypeScript
        run: npx tsc

      # Step 5: Prepare `dist` folder, but preserve folder structure.
      - name: Prepare Dist Folder
        run: |
          mkdir -p dist
          cp index.html dist/                # Copy the main HTML file
          cp -r src/scripts/compiledJS dist/compiledJS # Copy compiled JavaScript files
          cp -r style dist/style             # Copy the CSS styles

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
